//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 06/22/2015
//  @ Author : Team 2 josue de leon
//
//




public class Cliente extends Hotel {
	public Object public int rut;
	public Object public String nombre;
	public Object public int telefono;
	public Object public int cedula;
}
