//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hotel.java
//  @ Date : 06/22/2015
//  @ Author : Team 2 josue de leon
//
//




public class Hotel {
	public Object public int habitaciones;
	public Object public int reservadas;
	public Object public String categoria;
	public Object public int imagen;
	public void public hotel() {
	
	}
	
	public void public int piezasdisponibles() {
	
	}
	
	public void public double preciodepieza() {
	
	}
	
	public void public double descuento cliente() {
	
	}
	
	public void public double consultaprecio() {
	
	}
	
	public void public String reservapieza() {
	
	}
	
	public void public int imagenpieza() {
	
	}
	
	public void public boolean eliminarreservacion() {
	
	}
	
	public void public double cambiarprecio() {
	
	}
	
	public void public double cambiardescuento() {
	
	}
	
	public void public double ingresos() {
	
	}
}
