//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pieza.java
//  @ Date : 06/22/2015
//  @ Author : Team 2 josue de leon 
//
//




public class Pieza extends Hotel {
	public Object public int simple;
	public Object public int doble;
	public Object public int matrimonial;
	public Object public double precio;
	public Object public int numerodepieza;
	public void public int pieza() {
	
	}
	
	public void public double precio() {
	
	}
}
