//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reservacion.java
//  @ Date : 06/22/2015
//  @ Author : Team 2 josue de leon
//
//




public class Reservacion extends Hotel {
	public Object public String pieza;
	public Object public int fechadecomienzo;
	public Object public int dias;
	public Object public String cliente;
	public Object pulbic int fechadefinalizacion;
	public Object public int numerodepieza;
	public void public int imagenpieza() {
	
	}
}
